export {
  RESTDataSource,
  CacheOptions,
  DataSourceConfig,
  GetRequest,
  PatchRequest,
  PostRequest,
  PutRequest,
  DeleteRequest,
  HeadRequest,
  RequestWithoutBody,
  RequestWithBody,
  DataSourceRequest,
  RequestOptions,
  DataSourceResult,
  RequestDeduplicationPolicy,
} from './RESTDataSource';
